/**
 * Zero-trust helpers. Every piece of external content (resume text, job feeds,
 * AI output, user forms) passes through here before it is stored or displayed.
 */

// eslint-disable-next-line no-control-regex -- intentional: stripping control chars is the point
const CONTROL_CHARS = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g;

/** Strip control characters and collapse absurd whitespace. Output is plain text. */
export function cleanText(input: unknown, maxLength = 20000): string {
  if (typeof input !== "string") return "";
  return input
    .replace(CONTROL_CHARS, " ")
    .replace(/\r\n/g, "\n")
    .replace(/[ \t]{3,}/g, "  ")
    .replace(/\n{4,}/g, "\n\n\n")
    .trim()
    .slice(0, maxLength);
}

/**
 * Convert untrusted HTML (job feeds ship raw HTML) to safe plain text.
 * We never render feed HTML as markup — script/iframe/handler payloads simply
 * cannot survive this because the result is a text node.
 */
export function htmlToPlainText(input: unknown, maxLength = 20000): string {
  if (typeof input !== "string") return "";
  const withoutBlocks = input
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<(iframe|object|embed|svg|math)[\s\S]*?<\/\1>/gi, " ");

  const spaced = withoutBlocks
    .replace(/<\/(p|div|li|tr|h[1-6]|section|article)>/gi, "\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<li[^>]*>/gi, "• ")
    .replace(/<[^>]+>/g, " ");

  const decoded = spaced
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#0?39;|&apos;/gi, "'")
    .replace(/&#(\d+);/g, (_m, code: string) => {
      const n = Number(code);
      return n > 31 && n < 1114111 ? String.fromCodePoint(n) : " ";
    });

  return cleanText(decoded, maxLength);
}

const ALLOWED_PROTOCOLS = new Set(["http:", "https:"]);

/**
 * Only http/https URLs are ever surfaced. javascript:, data:, file:, vbscript:
 * and malformed values return null so the UI renders no link at all.
 */
export function safeExternalUrl(input: unknown): string | null {
  if (typeof input !== "string") return null;
  const trimmed = input.trim();
  if (!trimmed || trimmed.length > 2048) return null;
  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    return null;
  }
  if (!ALLOWED_PROTOCOLS.has(url.protocol)) return null;
  if (!url.hostname || url.hostname === "localhost") return null;
  return url.toString();
}

/** Same-origin relative path only — protects post-auth redirects. */
export function safeInternalPath(input: unknown, fallback = "/dashboard"): string {
  if (typeof input !== "string") return fallback;
  if (!input.startsWith("/") || input.startsWith("//")) return fallback;
  // eslint-disable-next-line no-control-regex -- intentional: reject control chars in paths
  if (/[\u0000-\u001F]/.test(input)) return fallback;
  return input;
}

/** Filenames are generated by us; the uploaded name is never trusted as a path. */
export function safeStorageName(userId: string, extension: "pdf" | "docx"): string {
  const random = crypto.randomUUID();
  return `${userId}/${Date.now()}-${random}.${extension}`;
}

export function displayFilename(input: unknown): string {
  const base = cleanText(input, 120).split(/[\\/]/).pop() ?? "";
  const safe = base.replace(/[^A-Za-z0-9._ -]/g, "").trim();
  return safe || "resume";
}

/**
 * Untrusted text is embedded in AI prompts inside explicit data fences with a
 * standing instruction that fenced content is data, never instructions.
 */
export function fenceUntrusted(label: string, content: string, maxLength = 14000): string {
  const cleaned = cleanText(content, maxLength).replace(/-{5,}/g, "-----");
  return `<<<BEGIN_UNTRUSTED_${label}>>>\n${cleaned}\n<<<END_UNTRUSTED_${label}>>>`;
}

export function clampScore(value: unknown): number {
  const n = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(100, Math.round(n)));
}

export function toStringArray(value: unknown, maxItems = 40, maxLength = 160): string[] {
  if (!Array.isArray(value)) return [];
  const out: string[] = [];
  for (const item of value) {
    const text = cleanText(typeof item === "string" ? item : "", maxLength);
    if (text) out.push(text);
    if (out.length >= maxItems) break;
  }
  return out;
}

/** Generic user-facing failure copy. Technical details stay in server logs. */
export const GENERIC_ERROR = "Something went wrong. Please try again.";
